# Generated by Django 3.2.5 on 2021-07-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Xl_store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('userid', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Xl_store',
            },
        ),
    ]
